os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - develop
    - master
    - main

before_install:
  - env | sort
  - dir="$(pwd)/images/${VERSION}/${VARIANT}"

install:
  - cd "$dir"
  # Execute CI build hooks
  - ./hooks/run build

before_script:
  # Display docker images
  - docker images

script:
  - cd "$dir"
  # Execute CI test hooks
  - ./hooks/run test

notifications:
  email: false

env: # Environments
    - VERSION=6.0 VARIANT=alpine
    - VERSION=6.1 VARIANT=alpine
    - VERSION=6.2 VARIANT=alpine
    - VERSION=6.3 VARIANT=alpine
    - VERSION=6.4 VARIANT=alpine
    - VERSION=6.5 VARIANT=alpine
